///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Sid_FCGAProject
{
    public partial class CG2028FormDetails
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
        public void CG2028FormsDetailsUserCodeMethod(RepoItemInfo inputtagInfo, RepoItemInfo inputtagInfo1, RepoItemInfo inputtagInfo2, RepoItemInfo inputtagInfo3, RepoItemInfo inputtagInfo4, RepoItemInfo inputtagInfo5, RepoItemInfo inputtagInfo6, RepoItemInfo inputtagInfo7, RepoItemInfo inputtagInfo8, RepoItemInfo inputtagInfo9, string CG2028No, RepoItemInfo inputtagInfo10, RepoItemInfo inputtagInfo11, RepoItemInfo inputtagInfo12, RepoItemInfo inputtagInfo13, RepoItemInfo inputtagInfo14)
        {
        	int CG2028N = Convert.ToInt32(CG2028No);
        	string[] CG2028_CompanyNameList = CG2028_CompanyName.Split(',');
        	string[] CG2028_Address1List = CG2028_Address1.Split(',');
        	string[] CG2028_Address2List = CG2028_Address2.Split(',');
        	string[] CG2028_CityList = CG2028_City.Split(',');
        	string[] CG2028_ZipCodeList = CG2028_ZipCode.Split(',');
        	
        	
        	for (int i=1;i<= CG2028N;i++)
        	{
        		
        	WebElement webElementItem = Host.Local.FindSingle<WebElement>("/dom[@domain<'fwcins.com']//div[#'divAdditionaldynamic']//input[@name='txtCompanyNameCG2028_"+i+"']");
        	webElementItem.Click();
        	webElementItem.PressKeys(CG2028_CompanyNameList[0]);
        	
        	WebElement webElementItem1 = Host.Local.FindSingle<WebElement>("/dom[@domain<'fwcins.com']//div[#'divAdditionaldynamic']//input[@name='txtAddress1CG2028_"+i+"']");
        	webElementItem1.Click();
        	webElementItem1.PressKeys(CG2028_Address1List[0]);	
        	
         	WebElement webElementItem2 = Host.Local.FindSingle<WebElement>("/dom[@domain<'fwcins.com']//div[#'divAdditionaldynamic']//input[@name='txtAddress2CG2028_"+i+"']");
        	webElementItem2.Click();
        	webElementItem2.PressKeys(CG2028_Address2List[0]);
        	
        	WebElement webElementItem3 = Host.Local.FindSingle<WebElement>("/dom[@domain<'fwcins.com']//div[#'divAdditionaldynamic']//input[@name='txtCityCG2028_"+i+"']");
        	webElementItem3.Click();
        	webElementItem3.PressKeys(CG2028_CityList[0]);

            WebElement webElementItem4 = Host.Local.FindSingle<WebElement>("/dom[@domain<'fwcins.com']//div[#'divAdditionaldynamic']//input[@name='txtZipCodeCG2028_"+i+"']");
        	webElementItem4.Click();
        	webElementItem4.PressKeys(CG2028_ZipCodeList[0]); 
        	}
        }
    }
}
