///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sid_FCGAProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CG2024FormDetails recording.
    /// </summary>
    [TestModule("443acf82-828c-46f0-ab22-1963293618b3", ModuleType.Recording, 1)]
    public partial class CG2024FormDetails : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repository.
        /// </summary>
        public static global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repo = global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository.Instance;

        static CG2024FormDetails instance = new CG2024FormDetails();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CG2024FormDetails()
        {
            CG2024_CompanyName = "XYZ";
            CG2024_Address1 = "Address1";
            CG2024_Address2 = "Address2";
            CG2024_City = "Tampa";
            CG2024_ZipCode = "33604";
            CG2024No = "1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CG2024FormDetails Instance
        {
            get { return instance; }
        }

#region Variables

        string _CG2024_CompanyName;

        /// <summary>
        /// Gets or sets the value of variable CG2024_CompanyName.
        /// </summary>
        [TestVariable("6f335a79-1e24-4e20-ad7c-2222ae147f6f")]
        public string CG2024_CompanyName
        {
            get { return _CG2024_CompanyName; }
            set { _CG2024_CompanyName = value; }
        }

        string _CG2024_Address1;

        /// <summary>
        /// Gets or sets the value of variable CG2024_Address1.
        /// </summary>
        [TestVariable("7f61f24d-3731-4df4-899a-3ab92f82252e")]
        public string CG2024_Address1
        {
            get { return _CG2024_Address1; }
            set { _CG2024_Address1 = value; }
        }

        string _CG2024_Address2;

        /// <summary>
        /// Gets or sets the value of variable CG2024_Address2.
        /// </summary>
        [TestVariable("9e47c1c5-3cb8-41c2-bc60-7a25c1337e29")]
        public string CG2024_Address2
        {
            get { return _CG2024_Address2; }
            set { _CG2024_Address2 = value; }
        }

        string _CG2024_City;

        /// <summary>
        /// Gets or sets the value of variable CG2024_City.
        /// </summary>
        [TestVariable("c7907c96-9ded-4e91-a3c4-cded4645306a")]
        public string CG2024_City
        {
            get { return _CG2024_City; }
            set { _CG2024_City = value; }
        }

        string _CG2024_ZipCode;

        /// <summary>
        /// Gets or sets the value of variable CG2024_ZipCode.
        /// </summary>
        [TestVariable("9f44d760-5147-4950-acad-07c81b522207")]
        public string CG2024_ZipCode
        {
            get { return _CG2024_ZipCode; }
            set { _CG2024_ZipCode = value; }
        }

        string _CG2024No;

        /// <summary>
        /// Gets or sets the value of variable CG2024No.
        /// </summary>
        [TestVariable("8f483e43-9c71-4bf1-a164-b321a6cd5ca7")]
        public string CG2024No
        {
            get { return _CG2024No; }
            set { _CG2024No = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            CG2024FormsDetailsUserCodeMethod(null, null, null, null, null, null, null, null, null, null, CG2024No, null, null, null, null, null);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
