///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sid_FCGAProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Endt_MailingAddressChange recording.
    /// </summary>
    [TestModule("893bed19-7ea8-4f3b-bb6a-344b556d93ae", ModuleType.Recording, 1)]
    public partial class Endt_MailingAddressChange : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repository.
        /// </summary>
        public static global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repo = global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository.Instance;

        static Endt_MailingAddressChange instance = new Endt_MailingAddressChange();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Endt_MailingAddressChange()
        {
            Endt_Mail_Address1 = "Address1";
            Endt_Mail_Address2 = "Address2";
            Endt_Mail_City = "Tampa";
            Endt_Mail_State = "Florida";
            Endt_Mail_ZipCode = "33604";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Endt_MailingAddressChange Instance
        {
            get { return instance; }
        }

#region Variables

        string _Endt_Mail_Address1;

        /// <summary>
        /// Gets or sets the value of variable Endt_Mail_Address1.
        /// </summary>
        [TestVariable("508931eb-bd47-45c0-a7ce-53d8f470737a")]
        public string Endt_Mail_Address1
        {
            get { return _Endt_Mail_Address1; }
            set { _Endt_Mail_Address1 = value; }
        }

        string _Endt_Mail_Address2;

        /// <summary>
        /// Gets or sets the value of variable Endt_Mail_Address2.
        /// </summary>
        [TestVariable("5587c7b2-4e3a-477e-97d9-01c4baebd67d")]
        public string Endt_Mail_Address2
        {
            get { return _Endt_Mail_Address2; }
            set { _Endt_Mail_Address2 = value; }
        }

        string _Endt_Mail_City;

        /// <summary>
        /// Gets or sets the value of variable Endt_Mail_City.
        /// </summary>
        [TestVariable("915403da-2a9c-4fb0-a4c4-eeed567c7e16")]
        public string Endt_Mail_City
        {
            get { return _Endt_Mail_City; }
            set { _Endt_Mail_City = value; }
        }

        string _Endt_Mail_State;

        /// <summary>
        /// Gets or sets the value of variable Endt_Mail_State.
        /// </summary>
        [TestVariable("d401ee10-0ba4-412b-b542-c928973bcf6d")]
        public string Endt_Mail_State
        {
            get { return _Endt_Mail_State; }
            set { _Endt_Mail_State = value; }
        }

        string _Endt_Mail_ZipCode;

        /// <summary>
        /// Gets or sets the value of variable Endt_Mail_ZipCode.
        /// </summary>
        [TestVariable("e84301ae-b283-4837-8f2e-572fbc7239ce")]
        public string Endt_Mail_ZipCode
        {
            get { return _Endt_Mail_ZipCode; }
            set { _Endt_Mail_ZipCode = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Border0CardRounded0.MailingBillingAddress' at Center.", repo.ApplicationUnderTest.Border0CardRounded0.MailingBillingAddressInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Border0CardRounded0.MailingBillingAddress.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Border0CardRounded0.TxtAddress1' at Center.", repo.ApplicationUnderTest.Border0CardRounded0.TxtAddress1Info, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Border0CardRounded0.TxtAddress1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Endt_Mail_Address1' with focus on 'ApplicationUnderTest.Border0CardRounded0.TxtAddress1'.", repo.ApplicationUnderTest.Border0CardRounded0.TxtAddress1Info, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Border0CardRounded0.TxtAddress1.PressKeys(Endt_Mail_Address1);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Border0CardRounded0.TxtAddress2' at Center.", repo.ApplicationUnderTest.Border0CardRounded0.TxtAddress2Info, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Border0CardRounded0.TxtAddress2.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Endt_Mail_Address2' with focus on 'ApplicationUnderTest.Border0CardRounded0.TxtAddress2'.", repo.ApplicationUnderTest.Border0CardRounded0.TxtAddress2Info, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Border0CardRounded0.TxtAddress2.PressKeys(Endt_Mail_Address2);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtCity' at Center.", repo.ApplicationUnderTest.TxtCityInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.TxtCity.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Endt_Mail_City' with focus on 'ApplicationUnderTest.TxtCity'.", repo.ApplicationUnderTest.TxtCityInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.TxtCity.PressKeys(Endt_Mail_City);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SelectGLState' at Center.", repo.ApplicationUnderTest.SelectGLStateInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.SelectGLState.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Search' at Center.", repo.ApplicationUnderTest.SearchInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.Search.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Endt_Mail_State' with focus on 'ApplicationUnderTest.Search'.", repo.ApplicationUnderTest.SearchInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.Search.PressKeys(Endt_Mail_State);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'ApplicationUnderTest.Search'.", repo.ApplicationUnderTest.SearchInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.Search.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeBodyTag' at Center.", repo.ApplicationUnderTest.SomeBodyTagInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.SomeBodyTag.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtZipCode' at Center.", repo.ApplicationUnderTest.TxtZipCodeInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.TxtZipCode.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Endt_Mail_ZipCode' with focus on 'ApplicationUnderTest.TxtZipCode'.", repo.ApplicationUnderTest.TxtZipCodeInfo, new RecordItemIndex(13));
            repo.ApplicationUnderTest.TxtZipCode.PressKeys(Endt_Mail_ZipCode);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
