///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sid_FCGAProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Endt_OPInReview recording.
    /// </summary>
    [TestModule("cb1eb35d-36af-43ec-ac75-13b7ba9d3943", ModuleType.Recording, 1)]
    public partial class Endt_OPInReview : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repository.
        /// </summary>
        public static global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repo = global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository.Instance;

        static Endt_OPInReview instance = new Endt_OPInReview();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Endt_OPInReview()
        {
            Endt_OPInReviewReason = "OK";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Endt_OPInReview Instance
        {
            get { return instance; }
        }

#region Variables

        string _Endt_OPInReviewReason;

        /// <summary>
        /// Gets or sets the value of variable Endt_OPInReviewReason.
        /// </summary>
        [TestVariable("a2673101-c3ab-49df-8d8f-6497b00045e9")]
        public string Endt_OPInReviewReason
        {
            get { return _Endt_OPInReviewReason; }
            set { _Endt_OPInReviewReason = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RbPendingtxt' at Center.", repo.ApplicationUnderTest.RbPendingtxtInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.RbPendingtxt.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtReason' at Center.", repo.ApplicationUnderTest.TxtReasonInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.TxtReason.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Endt_OPInReviewReason' with focus on 'ApplicationUnderTest.TxtReason'.", repo.ApplicationUnderTest.TxtReasonInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.TxtReason.PressKeys(Endt_OPInReviewReason);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
