///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sid_FCGAProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Endt_PrimaryAddressChange recording.
    /// </summary>
    [TestModule("2f8ccda2-1439-4068-8e44-0625da2c0d77", ModuleType.Recording, 1)]
    public partial class Endt_PrimaryAddressChange : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repository.
        /// </summary>
        public static global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repo = global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository.Instance;

        static Endt_PrimaryAddressChange instance = new Endt_PrimaryAddressChange();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Endt_PrimaryAddressChange()
        {
            Endt_Pri_Address1 = "Address1";
            Endt_Pri_Address2 = "Address2";
            Endt_Pri_City = "Tampa";
            Endt_Pri_State = "Florida";
            Endt_Pri_ZipCode = "33604";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Endt_PrimaryAddressChange Instance
        {
            get { return instance; }
        }

#region Variables

        string _Endt_Pri_Address1;

        /// <summary>
        /// Gets or sets the value of variable Endt_Pri_Address1.
        /// </summary>
        [TestVariable("58f0d38e-4198-4e18-9a94-078f121d4001")]
        public string Endt_Pri_Address1
        {
            get { return _Endt_Pri_Address1; }
            set { _Endt_Pri_Address1 = value; }
        }

        string _Endt_Pri_Address2;

        /// <summary>
        /// Gets or sets the value of variable Endt_Pri_Address2.
        /// </summary>
        [TestVariable("5a6e6f15-4b0d-4b6f-8e72-4a7aaad71988")]
        public string Endt_Pri_Address2
        {
            get { return _Endt_Pri_Address2; }
            set { _Endt_Pri_Address2 = value; }
        }

        string _Endt_Pri_City;

        /// <summary>
        /// Gets or sets the value of variable Endt_Pri_City.
        /// </summary>
        [TestVariable("c6a754a4-faf0-48f5-81c8-80d8cd4198a9")]
        public string Endt_Pri_City
        {
            get { return _Endt_Pri_City; }
            set { _Endt_Pri_City = value; }
        }

        string _Endt_Pri_State;

        /// <summary>
        /// Gets or sets the value of variable Endt_Pri_State.
        /// </summary>
        [TestVariable("58cc07ee-0c14-41ea-ae51-de5a9c42d82c")]
        public string Endt_Pri_State
        {
            get { return _Endt_Pri_State; }
            set { _Endt_Pri_State = value; }
        }

        string _Endt_Pri_ZipCode;

        /// <summary>
        /// Gets or sets the value of variable Endt_Pri_ZipCode.
        /// </summary>
        [TestVariable("24972566-0960-40c4-8f08-dbb8f6272021")]
        public string Endt_Pri_ZipCode
        {
            get { return _Endt_Pri_ZipCode; }
            set { _Endt_Pri_ZipCode = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Border0CardRounded0.PrimaryPhysical' at Center.", repo.ApplicationUnderTest.Border0CardRounded0.PrimaryPhysicalInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Border0CardRounded0.PrimaryPhysical.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Border0CardRounded0.TxtAddress1' at Center.", repo.ApplicationUnderTest.Border0CardRounded0.TxtAddress1Info, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Border0CardRounded0.TxtAddress1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Endt_Pri_Address1' with focus on 'ApplicationUnderTest.Border0CardRounded0.TxtAddress1'.", repo.ApplicationUnderTest.Border0CardRounded0.TxtAddress1Info, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Border0CardRounded0.TxtAddress1.PressKeys(Endt_Pri_Address1);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Border0CardRounded0.TxtAddress2' at Center.", repo.ApplicationUnderTest.Border0CardRounded0.TxtAddress2Info, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Border0CardRounded0.TxtAddress2.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Endt_Pri_Address2' with focus on 'ApplicationUnderTest.Border0CardRounded0.TxtAddress2'.", repo.ApplicationUnderTest.Border0CardRounded0.TxtAddress2Info, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Border0CardRounded0.TxtAddress2.PressKeys(Endt_Pri_Address2);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtCity' at Center.", repo.ApplicationUnderTest.TxtCityInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.TxtCity.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Endt_Pri_City' with focus on 'ApplicationUnderTest.TxtCity'.", repo.ApplicationUnderTest.TxtCityInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.TxtCity.PressKeys(Endt_Pri_City);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SelectGLState' at Center.", repo.ApplicationUnderTest.SelectGLStateInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.SelectGLState.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Search' at Center.", repo.ApplicationUnderTest.SearchInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.Search.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Endt_Pri_State' with focus on 'ApplicationUnderTest.Search'.", repo.ApplicationUnderTest.SearchInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.Search.PressKeys(Endt_Pri_State);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'ApplicationUnderTest.Search'.", repo.ApplicationUnderTest.SearchInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.Search.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeBodyTag' at Center.", repo.ApplicationUnderTest.SomeBodyTagInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.SomeBodyTag.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtZipCode' at Center.", repo.ApplicationUnderTest.TxtZipCodeInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.TxtZipCode.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Endt_Pri_ZipCode' with focus on 'ApplicationUnderTest.TxtZipCode'.", repo.ApplicationUnderTest.TxtZipCodeInfo, new RecordItemIndex(13));
            repo.ApplicationUnderTest.TxtZipCode.PressKeys(Endt_Pri_ZipCode);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
