///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sid_FCGAProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MakePayment recording.
    /// </summary>
    [TestModule("e27558a9-492c-49b5-ac8a-7bf2826cfb91", ModuleType.Recording, 1)]
    public partial class MakePayment : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repository.
        /// </summary>
        public static global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repo = global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository.Instance;

        static MakePayment instance = new MakePayment();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MakePayment()
        {
            WCInsuredAddress = "";
            Status_Reason = "Make Payment";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MakePayment Instance
        {
            get { return instance; }
        }

#region Variables

        string _WCInsuredAddress;

        /// <summary>
        /// Gets or sets the value of variable WCInsuredAddress.
        /// </summary>
        [TestVariable("6170a347-1774-498d-8e0e-77d1af562f6f")]
        public string WCInsuredAddress
        {
            get { return _WCInsuredAddress; }
            set { _WCInsuredAddress = value; }
        }

        string _Status_Reason;

        /// <summary>
        /// Gets or sets the value of variable Status_Reason.
        /// </summary>
        [TestVariable("cdc4d881-61f1-4117-a780-97c42d194850")]
        public string Status_Reason
        {
            get { return _Status_Reason; }
            set { _Status_Reason = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.WCInsuredAddress' at Center.", repo.ApplicationUnderTest.WCInsuredAddressInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.WCInsuredAddress.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.WCInsuredAddress' and assigning its value to variable 'WCInsuredAddress'.", repo.ApplicationUnderTest.WCInsuredAddressInfo, new RecordItemIndex(1));
            WCInsuredAddress = repo.ApplicationUnderTest.WCInsuredAddress.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BtnSave' at Center.", repo.ApplicationUnderTest.BtnSaveInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.BtnSave.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 15s to exist. Associated repository item: 'ApplicationUnderTest.Labelcheckbox'", repo.ApplicationUnderTest.LabelcheckboxInfo, new ActionTimeout(15000), new RecordItemIndex(3));
            repo.ApplicationUnderTest.LabelcheckboxInfo.WaitForExists(15000);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(4));
            Delay.Duration(5000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
