///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sid_FCGAProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The OutsideOccupationsMiscIQ recording.
    /// </summary>
    [TestModule("9ddf13fd-3df2-4786-8081-16b4205faf10", ModuleType.Recording, 1)]
    public partial class OutsideOccupationsMiscIQ : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repository.
        /// </summary>
        public static global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repo = global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository.Instance;

        static OutsideOccupationsMiscIQ instance = new OutsideOccupationsMiscIQ();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public OutsideOccupationsMiscIQ()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static OutsideOccupationsMiscIQ Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.HealthService.Accounting' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.HealthService.AccountingInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.IndustryQuestionTable.HealthService.Accounting.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.HealthService.Advertising' at 14;17.", repo.ApplicationUnderTest.IndustryQuestionTable.HealthService.AdvertisingInfo, new RecordItemIndex(1));
            //repo.ApplicationUnderTest.IndustryQuestionTable.HealthService.Advertising.Click("14;17");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.HealthService.ClaimAdjuster' at 10;16.", repo.ApplicationUnderTest.IndustryQuestionTable.HealthService.ClaimAdjusterInfo, new RecordItemIndex(2));
            //repo.ApplicationUnderTest.IndustryQuestionTable.HealthService.ClaimAdjuster.Click("10;16");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.HealthService.ComputerProgrammer' at 7;20.", repo.ApplicationUnderTest.IndustryQuestionTable.HealthService.ComputerProgrammerInfo, new RecordItemIndex(3));
            //repo.ApplicationUnderTest.IndustryQuestionTable.HealthService.ComputerProgrammer.Click("7;20");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.HealthService.ConstructionEstimator' at 10;23.", repo.ApplicationUnderTest.IndustryQuestionTable.HealthService.ConstructionEstimatorInfo, new RecordItemIndex(4));
            //repo.ApplicationUnderTest.IndustryQuestionTable.HealthService.ConstructionEstimator.Click("10;23");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.HealthService.ConsumerPackagedGoods' at 5;18.", repo.ApplicationUnderTest.IndustryQuestionTable.HealthService.ConsumerPackagedGoodsInfo, new RecordItemIndex(5));
            //repo.ApplicationUnderTest.IndustryQuestionTable.HealthService.ConsumerPackagedGoods.Click("5;18");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.HealthService.Courier' at 18;20.", repo.ApplicationUnderTest.IndustryQuestionTable.HealthService.CourierInfo, new RecordItemIndex(6));
            //repo.ApplicationUnderTest.IndustryQuestionTable.HealthService.Courier.Click("18;20");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.HealthService.FinancialServices' at 13;19.", repo.ApplicationUnderTest.IndustryQuestionTable.HealthService.FinancialServicesInfo, new RecordItemIndex(7));
            //repo.ApplicationUnderTest.IndustryQuestionTable.HealthService.FinancialServices.Click("13;19");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.HealthService.FreightBroker' at 13;25.", repo.ApplicationUnderTest.IndustryQuestionTable.HealthService.FreightBrokerInfo, new RecordItemIndex(8));
            //repo.ApplicationUnderTest.IndustryQuestionTable.HealthService.FreightBroker.Click("13;25");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.HealthService.Insurance' at 6;20.", repo.ApplicationUnderTest.IndustryQuestionTable.HealthService.InsuranceInfo, new RecordItemIndex(9));
            //repo.ApplicationUnderTest.IndustryQuestionTable.HealthService.Insurance.Click("6;20");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ApplicationUnderTest.IndustryQuestionTable.HealthService.InventoryCounter' at 13;22.", repo.ApplicationUnderTest.IndustryQuestionTable.HealthService.InventoryCounterInfo, new RecordItemIndex(10));
            //repo.ApplicationUnderTest.IndustryQuestionTable.HealthService.InventoryCounter.MoveTo("13;22");
            //Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ApplicationUnderTest.IndustryQuestionTable.HealthService.InventoryCounter' at 278;52.", repo.ApplicationUnderTest.IndustryQuestionTable.HealthService.InventoryCounterInfo, new RecordItemIndex(11));
            //repo.ApplicationUnderTest.IndustryQuestionTable.HealthService.InventoryCounter.MoveTo("278;52");
            //Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.LandSurveyor' at 6;19.", repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.LandSurveyorInfo, new RecordItemIndex(12));
            //repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.LandSurveyor.Click("6;19");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.LogisticsTransportationTrucking' at 17;16.", repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.LogisticsTransportationTruckingInfo, new RecordItemIndex(13));
            //repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.LogisticsTransportationTrucking.Click("17;16");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.ManufacturersRepresentative' at 6;19.", repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.ManufacturersRepresentativeInfo, new RecordItemIndex(14));
            //repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.ManufacturersRepresentative.Click("6;19");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.Marketing' at 12;16.", repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.MarketingInfo, new RecordItemIndex(15));
            //repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.Marketing.Click("12;16");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.MedicalDevices' at 9;20.", repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.MedicalDevicesInfo, new RecordItemIndex(16));
            //repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.MedicalDevices.Click("9;20");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.Pharmaceutical' at 13;15.", repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.PharmaceuticalInfo, new RecordItemIndex(17));
            //repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.Pharmaceutical.Click("13;15");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.PropertyAppraiser' at 9;21.", repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.PropertyAppraiserInfo, new RecordItemIndex(18));
            //repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.PropertyAppraiser.Click("9;21");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.PropertyInspection' at 6;18.", repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.PropertyInspectionInfo, new RecordItemIndex(19));
            //repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.PropertyInspection.Click("6;18");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.RealEstateAgent' at 8;19.", repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.RealEstateAgentInfo, new RecordItemIndex(20));
            //repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.RealEstateAgent.Click("8;19");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.SalesEngineer' at 13;18.", repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.SalesEngineerInfo, new RecordItemIndex(21));
            //repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.SalesEngineer.Click("13;18");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.Software' at 10;21.", repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.SoftwareInfo, new RecordItemIndex(22));
            //repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.Software.Click("10;21");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q1Other' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q1OtherInfo, new RecordItemIndex(23));
            repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q1Other.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q1OtherDesc' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q1OtherDescInfo, new RecordItemIndex(24));
            repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q1OtherDesc.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'OK' with focus on 'ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q1OtherDesc'.", repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q1OtherDescInfo, new RecordItemIndex(25));
            repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q1OtherDesc.PressKeys("OK");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q2Yes' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q2YesInfo, new RecordItemIndex(26));
            repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q2Yes.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q2No' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q2NoInfo, new RecordItemIndex(27));
            repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q2No.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q3Yes' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q3YesInfo, new RecordItemIndex(28));
            repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q3Yes.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q3No' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q3NoInfo, new RecordItemIndex(29));
            repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q3No.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q4Yes' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q4YesInfo, new RecordItemIndex(30));
            repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q4Yes.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q4No' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q4NoInfo, new RecordItemIndex(31));
            repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q4No.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q5Yes' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q5YesInfo, new RecordItemIndex(32));
            repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q5Yes.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q5No' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q5NoInfo, new RecordItemIndex(33));
            repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q5No.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q6Yes' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q6YesInfo, new RecordItemIndex(34));
            repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q6Yes.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q6No' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q6NoInfo, new RecordItemIndex(35));
            repo.ApplicationUnderTest.IndustryQuestionTable.OutsideOcupationsMisc.IQ_OutsideOccupations_Q6No.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BtnNext' at 44;14.", repo.ApplicationUnderTest.BtnNextInfo, new RecordItemIndex(36));
            repo.ApplicationUnderTest.BtnNext.Click("44;14");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
