///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sid_FCGAProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The UW_OtherEndtFormCG2029 recording.
    /// </summary>
    [TestModule("13bf7511-f814-4c38-96e9-c009eee85137", ModuleType.Recording, 1)]
    public partial class UW_OtherEndtFormCG2029 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repository.
        /// </summary>
        public static global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repo = global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository.Instance;

        static UW_OtherEndtFormCG2029 instance = new UW_OtherEndtFormCG2029();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public UW_OtherEndtFormCG2029()
        {
            UWCG2029_No = "1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static UW_OtherEndtFormCG2029 Instance
        {
            get { return instance; }
        }

#region Variables

        string _UWCG2029_No;

        /// <summary>
        /// Gets or sets the value of variable UWCG2029_No.
        /// </summary>
        [TestVariable("793cd69f-7ad9-49f2-80da-d38234d7adcd")]
        public string UWCG2029_No
        {
            get { return _UWCG2029_No; }
            set { _UWCG2029_No = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Text4' at Center.", repo.ApplicationUnderTest.Text4Info, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Text4.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '(null)' on item 'ApplicationUnderTest.Text4'.", repo.ApplicationUnderTest.Text4Info, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Text4.Element.SetAttributeValue("Value", null);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$UWCG2029_No' with focus on 'ApplicationUnderTest.Text4'.", repo.ApplicationUnderTest.Text4Info, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Text4.PressKeys(UWCG2029_No);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
