///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Sid_FCGAProject.Project_Repository
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Common_repo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("51ef24ff-d60d-4f02-8550-06169a5f31ae")]
    public partial class Common_repo : RepoGenBaseFolder
    {
        static Common_repo instance = new Common_repo();
        Common_repoFolders.RecordsViewAppFolder _recordsview;
        Common_repoFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the Common_repo element repository.
        /// </summary>
        [RepositoryFolder("51ef24ff-d60d-4f02-8550-06169a5f31ae")]
        public static Common_repo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Common_repo() 
            : base("Common_repo", "/", null, 0, false, "51ef24ff-d60d-4f02-8550-06169a5f31ae", ".\\RepositoryImages\\Common_repo51ef24ff.rximgres")
        {
            _recordsview = new Common_repoFolders.RecordsViewAppFolder(this);
            _applicationundertest = new Common_repoFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

        string _QA_Agent_Env = "https://qawinston.fwcins.com/FWCPortal/User/Login/Login.html";

        /// <summary>
        /// Gets or sets the value of variable QA_Agent_Env.
        /// </summary>
        [TestVariable("0c1e36ea-c859-4769-8592-9645835e4c0c")]
        public string QA_Agent_Env
        {
            get { return _QA_Agent_Env; }
            set { _QA_Agent_Env = value; }
        }

        string _Iteration = "1";

        /// <summary>
        /// Gets or sets the value of variable Iteration.
        /// </summary>
        [TestVariable("aab9529b-212f-49f5-982e-205dea44466e")]
        public string Iteration
        {
            get { return _Iteration; }
            set { _Iteration = value; }
        }

        string _ClassCode_CS = "91127";

        /// <summary>
        /// Gets or sets the value of variable ClassCode_CS.
        /// </summary>
        [TestVariable("731966be-356c-4696-abbc-07840ba06fa2")]
        public string ClassCode_CS
        {
            get { return _ClassCode_CS; }
            set { _ClassCode_CS = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("51ef24ff-d60d-4f02-8550-06169a5f31ae")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RecordsView folder.
        /// </summary>
        [RepositoryFolder("bdb6190a-a9fa-4dd7-8f97-29827e934463")]
        public virtual Common_repoFolders.RecordsViewAppFolder RecordsView
        {
            get { return _recordsview; }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("773e42af-daa3-4b58-b660-a4b72aba4cc5")]
        public virtual Common_repoFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Common_repoFolders
    {
        /// <summary>
        /// The RecordsViewAppFolder folder.
        /// </summary>
        [RepositoryFolder("bdb6190a-a9fa-4dd7-8f97-29827e934463")]
        public partial class RecordsViewAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _chrome_closedInfo;

            /// <summary>
            /// Creates a new RecordsView  folder.
            /// </summary>
            public RecordsViewAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RecordsView", "/dom[@domain='qawinston.fwcins.com']", parentFolder, 30000, null, false, "bdb6190a-a9fa-4dd7-8f97-29827e934463", "")
            {
                _chrome_closedInfo = new RepoItemInfo(this, "Chrome_Closed", "body", "", 30000, null, "7242ee16-205e-462b-9330-5e90c0d96fb0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bdb6190a-a9fa-4dd7-8f97-29827e934463")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bdb6190a-a9fa-4dd7-8f97-29827e934463")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Chrome_Closed item.
            /// </summary>
            [RepositoryItem("7242ee16-205e-462b-9330-5e90c0d96fb0")]
            public virtual Ranorex.BodyTag Chrome_Closed
            {
                get
                {
                    return _chrome_closedInfo.CreateAdapter<Ranorex.BodyTag>(true);
                }
            }

            /// <summary>
            /// The Chrome_Closed item info.
            /// </summary>
            [RepositoryItemInfo("7242ee16-205e-462b-9330-5e90c0d96fb0")]
            public virtual RepoItemInfo Chrome_ClosedInfo
            {
                get
                {
                    return _chrome_closedInfo;
                }
            }
        }

        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("773e42af-daa3-4b58-b660-a4b72aba4cc5")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            Common_repoFolders.Class_Specific_SelectionFolder _class_specific_selection;
            Common_repoFolders.MyTableFolder _mytable;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain<'fwcins.com']", parentFolder, 30000, null, false, "773e42af-daa3-4b58-b660-a4b72aba4cc5", "")
            {
                _class_specific_selection = new Common_repoFolders.Class_Specific_SelectionFolder(this);
                _mytable = new Common_repoFolders.MyTableFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("773e42af-daa3-4b58-b660-a4b72aba4cc5")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("773e42af-daa3-4b58-b660-a4b72aba4cc5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Class_Specific_Selection folder.
            /// </summary>
            [RepositoryFolder("9aa56d92-af24-42b8-93ea-0b9a955f3cec")]
            public virtual Common_repoFolders.Class_Specific_SelectionFolder Class_Specific_Selection
            {
                get { return _class_specific_selection; }
            }

            /// <summary>
            /// The MyTable folder.
            /// </summary>
            [RepositoryFolder("e5f3ad36-a296-400c-a0f7-f07e2720cc18")]
            public virtual Common_repoFolders.MyTableFolder MyTable
            {
                get { return _mytable; }
            }
        }

        /// <summary>
        /// The Class_Specific_SelectionFolder folder.
        /// </summary>
        [RepositoryFolder("9aa56d92-af24-42b8-93ea-0b9a955f3cec")]
        public partial class Class_Specific_SelectionFolder : RepoGenBaseFolder
        {
            RepoItemInfo _copy_of_class_specific_q1noInfo;

            /// <summary>
            /// Creates a new Class_Specific_Selection  folder.
            /// </summary>
            public Class_Specific_SelectionFolder(RepoGenBaseFolder parentFolder) :
                    base("Class_Specific_Selection", "", parentFolder, 0, null, false, "9aa56d92-af24-42b8-93ea-0b9a955f3cec", "")
            {
                _copy_of_class_specific_q1noInfo = new RepoItemInfo(this, "Copy_of_Class_Specific_Q1No", ".//table[#'myTable']/tbody//td[7]/?/?/label[@innertext='No'][$Iteration]", "", 30000, null, "826eb148-5045-4293-8863-44bb2d79bd14");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9aa56d92-af24-42b8-93ea-0b9a955f3cec")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Copy_of_Class_Specific_Q1No item.
            /// </summary>
            [RepositoryItem("826eb148-5045-4293-8863-44bb2d79bd14")]
            public virtual Ranorex.LabelTag Copy_of_Class_Specific_Q1No
            {
                get
                {
                    return _copy_of_class_specific_q1noInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The Copy_of_Class_Specific_Q1No item info.
            /// </summary>
            [RepositoryItemInfo("826eb148-5045-4293-8863-44bb2d79bd14")]
            public virtual RepoItemInfo Copy_of_Class_Specific_Q1NoInfo
            {
                get
                {
                    return _copy_of_class_specific_q1noInfo;
                }
            }
        }

        /// <summary>
        /// The MyTableFolder folder.
        /// </summary>
        [RepositoryFolder("e5f3ad36-a296-400c-a0f7-f07e2720cc18")]
        public partial class MyTableFolder : RepoGenBaseFolder
        {
            RepoItemInfo _copy_of_class_specific_q1Info;

            /// <summary>
            /// Creates a new MyTable  folder.
            /// </summary>
            public MyTableFolder(RepoGenBaseFolder parentFolder) :
                    base("MyTable", ".//table[#'myTable']", parentFolder, 30000, null, false, "e5f3ad36-a296-400c-a0f7-f07e2720cc18", "")
            {
                _copy_of_class_specific_q1Info = new RepoItemInfo(this, "Copy_of_Class_Specific_Q1", "tbody/?/?/td[@innertext>$ClassCode_CS][$Iteration]", "", 30000, null, "00ff60ba-e545-47ca-bab5-ea1df9dc38c6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e5f3ad36-a296-400c-a0f7-f07e2720cc18")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e5f3ad36-a296-400c-a0f7-f07e2720cc18")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Copy_of_Class_Specific_Q1 item.
            /// </summary>
            [RepositoryItem("00ff60ba-e545-47ca-bab5-ea1df9dc38c6")]
            public virtual Ranorex.TdTag Copy_of_Class_Specific_Q1
            {
                get
                {
                    return _copy_of_class_specific_q1Info.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The Copy_of_Class_Specific_Q1 item info.
            /// </summary>
            [RepositoryItemInfo("00ff60ba-e545-47ca-bab5-ea1df9dc38c6")]
            public virtual RepoItemInfo Copy_of_Class_Specific_Q1Info
            {
                get
                {
                    return _copy_of_class_specific_q1Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
