///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sid_FCGAProject.GL_Product
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CG2029FormDetails recording.
    /// </summary>
    [TestModule("63230a2e-e9a4-474b-8292-fc5fdb9eee4b", ModuleType.Recording, 1)]
    public partial class CG2029FormDetails : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repository.
        /// </summary>
        public static global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repo = global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository.Instance;

        static CG2029FormDetails instance = new CG2029FormDetails();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CG2029FormDetails()
        {
            CG2029_CompanyName = "CG2029";
            CG2029_Address1 = "Address1";
            CG2029_Address2 = "Address2";
            CG2029_City = "Tampa";
            CG2029_ZipCode = "33604";
            CG2029No = "2";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CG2029FormDetails Instance
        {
            get { return instance; }
        }

#region Variables

        string _CG2029_CompanyName;

        /// <summary>
        /// Gets or sets the value of variable CG2029_CompanyName.
        /// </summary>
        [TestVariable("a040d8fd-2bcc-4a3a-aa45-aaa8ef125c83")]
        public string CG2029_CompanyName
        {
            get { return _CG2029_CompanyName; }
            set { _CG2029_CompanyName = value; }
        }

        string _CG2029_Address1;

        /// <summary>
        /// Gets or sets the value of variable CG2029_Address1.
        /// </summary>
        [TestVariable("dbbd42b7-9927-44b9-85cf-686a82991a54")]
        public string CG2029_Address1
        {
            get { return _CG2029_Address1; }
            set { _CG2029_Address1 = value; }
        }

        string _CG2029_Address2;

        /// <summary>
        /// Gets or sets the value of variable CG2029_Address2.
        /// </summary>
        [TestVariable("8824ee22-f27c-4288-a860-8b1038f98a49")]
        public string CG2029_Address2
        {
            get { return _CG2029_Address2; }
            set { _CG2029_Address2 = value; }
        }

        string _CG2029_City;

        /// <summary>
        /// Gets or sets the value of variable CG2029_City.
        /// </summary>
        [TestVariable("c45718a3-140b-4e59-a0b0-98fcccab5676")]
        public string CG2029_City
        {
            get { return _CG2029_City; }
            set { _CG2029_City = value; }
        }

        string _CG2029_ZipCode;

        /// <summary>
        /// Gets or sets the value of variable CG2029_ZipCode.
        /// </summary>
        [TestVariable("1c9f1ba6-7238-48a7-a01b-ffdcf4eafbc1")]
        public string CG2029_ZipCode
        {
            get { return _CG2029_ZipCode; }
            set { _CG2029_ZipCode = value; }
        }

        string _CG2029No;

        /// <summary>
        /// Gets or sets the value of variable CG2029No.
        /// </summary>
        [TestVariable("40382ac7-686a-4c3c-953b-ed4923d190cf")]
        public string CG2029No
        {
            get { return _CG2029No; }
            set { _CG2029No = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            MergedUserCodeMethod(repo.ApplicationUnderTest.TxtCompanyNameCG2029Info, repo.ApplicationUnderTest.TxtAddress1CG2029Info, repo.ApplicationUnderTest.TxtAddress2CG2029Info, repo.ApplicationUnderTest.TxtCityCG2029Info, repo.ApplicationUnderTest.TxtZipCodeCG2029Info, repo.ApplicationUnderTest.TxtCompanyNameCG20291Info, repo.ApplicationUnderTest.TxtAddress1CG20291Info, repo.ApplicationUnderTest.TxtAddress2CG20291Info, repo.ApplicationUnderTest.TxtCityCG20291Info, repo.ApplicationUnderTest.TxtZipCodeCG20291Info, repo.ApplicationUnderTest.TxtCompanyNameCG20292Info, repo.ApplicationUnderTest.TxtAddress1CG20292Info, repo.ApplicationUnderTest.TxtAddress2CG20292Info, repo.ApplicationUnderTest.TxtCityCG20292Info, repo.ApplicationUnderTest.TxtZipCodeCG20292Info, CG2029No);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
