///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sid_FCGAProject.GL_Product
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FCG1019FormDetails recording.
    /// </summary>
    [TestModule("4869d257-d57c-4d97-9238-c1fbcb3c0832", ModuleType.Recording, 1)]
    public partial class FCG1019FormDetails : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repository.
        /// </summary>
        public static global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repo = global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository.Instance;

        static FCG1019FormDetails instance = new FCG1019FormDetails();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FCG1019FormDetails()
        {
            FCG1019_CompanyName = "FCG1019";
            FCG1019_Address1 = "Address1";
            FCG1019_Address2 = "Address2";
            FCG1019_City = "tampa";
            FCG1019_ZipCode = "33604";
            FCG1019No = "1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FCG1019FormDetails Instance
        {
            get { return instance; }
        }

#region Variables

        string _FCG1019_CompanyName;

        /// <summary>
        /// Gets or sets the value of variable FCG1019_CompanyName.
        /// </summary>
        [TestVariable("5226c78e-186b-4d5a-93c1-23f1abf0b81c")]
        public string FCG1019_CompanyName
        {
            get { return _FCG1019_CompanyName; }
            set { _FCG1019_CompanyName = value; }
        }

        string _FCG1019_Address1;

        /// <summary>
        /// Gets or sets the value of variable FCG1019_Address1.
        /// </summary>
        [TestVariable("7d3f1308-5264-4e2e-8f71-2ebcd50e3e12")]
        public string FCG1019_Address1
        {
            get { return _FCG1019_Address1; }
            set { _FCG1019_Address1 = value; }
        }

        string _FCG1019_Address2;

        /// <summary>
        /// Gets or sets the value of variable FCG1019_Address2.
        /// </summary>
        [TestVariable("ac0570d7-7822-43c5-8ee7-e0eb8bcfd020")]
        public string FCG1019_Address2
        {
            get { return _FCG1019_Address2; }
            set { _FCG1019_Address2 = value; }
        }

        string _FCG1019_City;

        /// <summary>
        /// Gets or sets the value of variable FCG1019_City.
        /// </summary>
        [TestVariable("f8d2dce2-8a59-40b7-a56d-90a87c3d9c23")]
        public string FCG1019_City
        {
            get { return _FCG1019_City; }
            set { _FCG1019_City = value; }
        }

        string _FCG1019_ZipCode;

        /// <summary>
        /// Gets or sets the value of variable FCG1019_ZipCode.
        /// </summary>
        [TestVariable("8f6eb75d-e795-4314-b639-b25c6fd39da9")]
        public string FCG1019_ZipCode
        {
            get { return _FCG1019_ZipCode; }
            set { _FCG1019_ZipCode = value; }
        }

        string _FCG1019No;

        /// <summary>
        /// Gets or sets the value of variable FCG1019No.
        /// </summary>
        [TestVariable("aceee2ca-e190-483c-b49b-879d4fda151e")]
        public string FCG1019No
        {
            get { return _FCG1019No; }
            set { _FCG1019No = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Header text
            FCG1019FormDetailsUserCodeMethod(repo.ApplicationUnderTest.TxtCompanyNameFCG1019Info, repo.ApplicationUnderTest.TxtAddress1FCG1019Info, repo.ApplicationUnderTest.TxtAddress2FCG1019Info, repo.ApplicationUnderTest.TxtCityFCG1019Info, repo.ApplicationUnderTest.TxtZipCodeFCG1019Info, repo.ApplicationUnderTest.TxtCompanyNameFCG10191Info, repo.ApplicationUnderTest.TxtAddress1FCG10191Info, repo.ApplicationUnderTest.TxtAddress2FCG10191Info, repo.ApplicationUnderTest.TxtCityFCG10191Info, repo.ApplicationUnderTest.TxtZipCodeFCG10191Info, repo.ApplicationUnderTest.TxtCompanyNameFCG10192Info, repo.ApplicationUnderTest.TxtAddress1FCG10192Info, repo.ApplicationUnderTest.TxtAddress2FCG10192Info, repo.ApplicationUnderTest.TxtCityFCG10192Info, repo.ApplicationUnderTest.TxtZipCodeFCG10192Info, FCG1019No);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
