///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sid_FCGAProject.GL_Product
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GL_ApplicationPageP1 recording.
    /// </summary>
    [TestModule("67cec58b-c116-418c-8d83-a9bdc626eea5", ModuleType.Recording, 1)]
    public partial class GL_ApplicationPageP1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repository.
        /// </summary>
        public static global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repo = global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository.Instance;

        static GL_ApplicationPageP1 instance = new GL_ApplicationPageP1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GL_ApplicationPageP1()
        {
            GL_BusinessType = "Corporation";
            GL_InspectionOfficer = "OK";
            GL_Address1 = "Address1";
            GL_Address2 = "Address2";
            GL_City = "Tampa";
            GL_Zipcode = "33604";
            GL_Business_PhoneNo = "9937756887";
            GL_BusinessFax = "9936767588";
            GL_BusinessEmail = "siddharthm@pmam.com";
            GL_Business_Web_Add = "www,google.com";
            GL_FEINNo = "654654645";
            GL_MailingAddress1 = "Address1";
            GL_MailingAddress2 = "Address1";
            GL_CityName = "Tampa";
            GL_MailingZipcode = "33604";
            GL_MailingStateName = "FL";
            GL_ExpirationDate = "08/03/2021";
            GL_InsuranceCarrier = "OK";
            GL_GeneralRemark = "OK";
            FullAddress = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GL_ApplicationPageP1 Instance
        {
            get { return instance; }
        }

#region Variables

        string _GL_BusinessType;

        /// <summary>
        /// Gets or sets the value of variable GL_BusinessType.
        /// </summary>
        [TestVariable("3b53a0d5-33c6-4252-9c70-f0c7c05efbbf")]
        public string GL_BusinessType
        {
            get { return _GL_BusinessType; }
            set { _GL_BusinessType = value; }
        }

        string _GL_InspectionOfficer;

        /// <summary>
        /// Gets or sets the value of variable GL_InspectionOfficer.
        /// </summary>
        [TestVariable("ff570488-b28a-460c-ba67-0a68af8ade56")]
        public string GL_InspectionOfficer
        {
            get { return _GL_InspectionOfficer; }
            set { _GL_InspectionOfficer = value; }
        }

        string _GL_Address1;

        /// <summary>
        /// Gets or sets the value of variable GL_Address1.
        /// </summary>
        [TestVariable("ae23bcc1-09e0-4186-a09b-55ae7ee134ec")]
        public string GL_Address1
        {
            get { return _GL_Address1; }
            set { _GL_Address1 = value; }
        }

        string _GL_Address2;

        /// <summary>
        /// Gets or sets the value of variable GL_Address2.
        /// </summary>
        [TestVariable("b0f0751e-43a5-4813-b3e2-71fb9e8160af")]
        public string GL_Address2
        {
            get { return _GL_Address2; }
            set { _GL_Address2 = value; }
        }

        string _GL_City;

        /// <summary>
        /// Gets or sets the value of variable GL_City.
        /// </summary>
        [TestVariable("b9d74ffa-5dd4-4988-83bf-d74560697b44")]
        public string GL_City
        {
            get { return _GL_City; }
            set { _GL_City = value; }
        }

        string _GL_Zipcode;

        /// <summary>
        /// Gets or sets the value of variable GL_Zipcode.
        /// </summary>
        [TestVariable("e9856298-1c45-4f9b-b512-b71fa53d590d")]
        public string GL_Zipcode
        {
            get { return _GL_Zipcode; }
            set { _GL_Zipcode = value; }
        }

        string _GL_Business_PhoneNo;

        /// <summary>
        /// Gets or sets the value of variable GL_Business_PhoneNo.
        /// </summary>
        [TestVariable("8e9be469-e387-4d64-a109-3d32de5e99f4")]
        public string GL_Business_PhoneNo
        {
            get { return _GL_Business_PhoneNo; }
            set { _GL_Business_PhoneNo = value; }
        }

        string _GL_BusinessFax;

        /// <summary>
        /// Gets or sets the value of variable GL_BusinessFax.
        /// </summary>
        [TestVariable("963bb065-29f4-49d8-8fa4-06f57e5d598e")]
        public string GL_BusinessFax
        {
            get { return _GL_BusinessFax; }
            set { _GL_BusinessFax = value; }
        }

        string _GL_BusinessEmail;

        /// <summary>
        /// Gets or sets the value of variable GL_BusinessEmail.
        /// </summary>
        [TestVariable("07df3a70-a627-49ad-aee9-b2d6f87ee693")]
        public string GL_BusinessEmail
        {
            get { return _GL_BusinessEmail; }
            set { _GL_BusinessEmail = value; }
        }

        string _GL_Business_Web_Add;

        /// <summary>
        /// Gets or sets the value of variable GL_Business_Web_Add.
        /// </summary>
        [TestVariable("3b16aa7c-644f-454c-80d1-bdace0521990")]
        public string GL_Business_Web_Add
        {
            get { return _GL_Business_Web_Add; }
            set { _GL_Business_Web_Add = value; }
        }

        string _GL_FEINNo;

        /// <summary>
        /// Gets or sets the value of variable GL_FEINNo.
        /// </summary>
        [TestVariable("167a1820-3928-4ec1-82bb-8ac61ce4220e")]
        public string GL_FEINNo
        {
            get { return _GL_FEINNo; }
            set { _GL_FEINNo = value; }
        }

        string _GL_MailingAddress1;

        /// <summary>
        /// Gets or sets the value of variable GL_MailingAddress1.
        /// </summary>
        [TestVariable("a43ad89e-15b3-4d6b-8268-c0db0e2b183e")]
        public string GL_MailingAddress1
        {
            get { return _GL_MailingAddress1; }
            set { _GL_MailingAddress1 = value; }
        }

        string _GL_MailingAddress2;

        /// <summary>
        /// Gets or sets the value of variable GL_MailingAddress2.
        /// </summary>
        [TestVariable("19baf6b6-b160-454a-ab21-743f05a081ea")]
        public string GL_MailingAddress2
        {
            get { return _GL_MailingAddress2; }
            set { _GL_MailingAddress2 = value; }
        }

        string _GL_CityName;

        /// <summary>
        /// Gets or sets the value of variable GL_CityName.
        /// </summary>
        [TestVariable("c6a25685-9780-4c3f-91f1-706c6682d99a")]
        public string GL_CityName
        {
            get { return _GL_CityName; }
            set { _GL_CityName = value; }
        }

        string _GL_MailingZipcode;

        /// <summary>
        /// Gets or sets the value of variable GL_MailingZipcode.
        /// </summary>
        [TestVariable("dd3439a7-10db-4779-bff0-5a8114ba2ac1")]
        public string GL_MailingZipcode
        {
            get { return _GL_MailingZipcode; }
            set { _GL_MailingZipcode = value; }
        }

        string _GL_MailingStateName;

        /// <summary>
        /// Gets or sets the value of variable GL_MailingStateName.
        /// </summary>
        [TestVariable("502275a6-44a9-42af-afa8-8b571577a22f")]
        public string GL_MailingStateName
        {
            get { return _GL_MailingStateName; }
            set { _GL_MailingStateName = value; }
        }

        string _GL_ExpirationDate;

        /// <summary>
        /// Gets or sets the value of variable GL_ExpirationDate.
        /// </summary>
        [TestVariable("ca4da884-17cb-44e0-81a5-8906d5961ad8")]
        public string GL_ExpirationDate
        {
            get { return _GL_ExpirationDate; }
            set { _GL_ExpirationDate = value; }
        }

        string _GL_InsuranceCarrier;

        /// <summary>
        /// Gets or sets the value of variable GL_InsuranceCarrier.
        /// </summary>
        [TestVariable("a2dcecbf-31f6-4fe8-b1c2-880a58797c86")]
        public string GL_InsuranceCarrier
        {
            get { return _GL_InsuranceCarrier; }
            set { _GL_InsuranceCarrier = value; }
        }

        string _GL_GeneralRemark;

        /// <summary>
        /// Gets or sets the value of variable GL_GeneralRemark.
        /// </summary>
        [TestVariable("96758d47-5b23-4741-b613-4ccdb98f1161")]
        public string GL_GeneralRemark
        {
            get { return _GL_GeneralRemark; }
            set { _GL_GeneralRemark = value; }
        }

        string _FullAddress;

        /// <summary>
        /// Gets or sets the value of variable FullAddress.
        /// </summary>
        [TestVariable("06a7825d-3f4f-42fe-aa17-532e6b9fcc4d")]
        public string FullAddress
        {
            get { return _FullAddress; }
            set { _FullAddress = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Select2DdlBusinessTypeContainer' at Center.", repo.ApplicationUnderTest.Select2DdlBusinessTypeContainerInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Select2DdlBusinessTypeContainer.Click();
            Delay.Milliseconds(0);
            
            FullAddress = FullAddress1(GL_Address1, GL_Address2, GL_City, GL_Zipcode);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Search' at Center.", repo.ApplicationUnderTest.SearchInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Search.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$GL_BusinessType' with focus on 'ApplicationUnderTest.Search'.", repo.ApplicationUnderTest.SearchInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Search.PressKeys(GL_BusinessType);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'ApplicationUnderTest.Search'.", repo.ApplicationUnderTest.SearchInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Search.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtInspectionContact' at 45;21.", repo.ApplicationUnderTest.TxtInspectionContactInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.TxtInspectionContact.Click("45;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$GL_InspectionOfficer' with focus on 'ApplicationUnderTest.TxtInspectionContact'.", repo.ApplicationUnderTest.TxtInspectionContactInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.TxtInspectionContact.PressKeys(GL_InspectionOfficer);
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BgGrey2CardBody.TxtLocationAddress1' at 135;14.", repo.ApplicationUnderTest.BgGrey2CardBody.TxtLocationAddress1Info, new RecordItemIndex(7));
            //repo.ApplicationUnderTest.BgGrey2CardBody.TxtLocationAddress1.Click("135;14");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$GL_Address1' with focus on 'ApplicationUnderTest.BgGrey2CardBody.TxtLocationAddress1'.", repo.ApplicationUnderTest.BgGrey2CardBody.TxtLocationAddress1Info, new RecordItemIndex(8));
            //repo.ApplicationUnderTest.BgGrey2CardBody.TxtLocationAddress1.PressKeys(GL_Address1);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BgGrey2CardBody.TxtLocationAddress2' at 34;13.", repo.ApplicationUnderTest.BgGrey2CardBody.TxtLocationAddress2Info, new RecordItemIndex(9));
            //repo.ApplicationUnderTest.BgGrey2CardBody.TxtLocationAddress2.Click("34;13");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$GL_Address2' with focus on 'ApplicationUnderTest.BgGrey2CardBody.TxtLocationAddress2'.", repo.ApplicationUnderTest.BgGrey2CardBody.TxtLocationAddress2Info, new RecordItemIndex(10));
            //repo.ApplicationUnderTest.BgGrey2CardBody.TxtLocationAddress2.PressKeys(GL_Address2);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtLocationCity' at Center.", repo.ApplicationUnderTest.TxtLocationCityInfo, new RecordItemIndex(11));
            //repo.ApplicationUnderTest.TxtLocationCity.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$GL_City' with focus on 'ApplicationUnderTest.TxtLocationCity'.", repo.ApplicationUnderTest.TxtLocationCityInfo, new RecordItemIndex(12));
            //repo.ApplicationUnderTest.TxtLocationCity.PressKeys(GL_City);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtLocationZipCode' at Center.", repo.ApplicationUnderTest.TxtLocationZipCodeInfo, new RecordItemIndex(13));
            //repo.ApplicationUnderTest.TxtLocationZipCode.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$GL_Zipcode' with focus on 'ApplicationUnderTest.TxtLocationZipCode'.", repo.ApplicationUnderTest.TxtLocationZipCodeInfo, new RecordItemIndex(14));
            //repo.ApplicationUnderTest.TxtLocationZipCode.PressKeys(GL_Zipcode);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(15));
            //Delay.Duration(3000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MainContentHolder.UseAsIs' at Center.", repo.ApplicationUnderTest.MainContentHolder.UseAsIsInfo, new RecordItemIndex(16));
            //repo.ApplicationUnderTest.MainContentHolder.UseAsIs.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtBusinessPhone' at 161;15.", repo.ApplicationUnderTest.TxtBusinessPhoneInfo, new RecordItemIndex(17));
            repo.ApplicationUnderTest.TxtBusinessPhone.Click("161;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$GL_Business_PhoneNo' with focus on 'ApplicationUnderTest.TxtBusinessPhone'.", repo.ApplicationUnderTest.TxtBusinessPhoneInfo, new RecordItemIndex(18));
            repo.ApplicationUnderTest.TxtBusinessPhone.PressKeys(GL_Business_PhoneNo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtBusinessFax' at Center.", repo.ApplicationUnderTest.TxtBusinessFaxInfo, new RecordItemIndex(19));
            repo.ApplicationUnderTest.TxtBusinessFax.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$GL_BusinessFax' with focus on 'ApplicationUnderTest.TxtBusinessFax'.", repo.ApplicationUnderTest.TxtBusinessFaxInfo, new RecordItemIndex(20));
            repo.ApplicationUnderTest.TxtBusinessFax.PressKeys(GL_BusinessFax);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtBusinessEmail' at Center.", repo.ApplicationUnderTest.TxtBusinessEmailInfo, new RecordItemIndex(21));
            repo.ApplicationUnderTest.TxtBusinessEmail.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$GL_BusinessEmail' with focus on 'ApplicationUnderTest.TxtBusinessEmail'.", repo.ApplicationUnderTest.TxtBusinessEmailInfo, new RecordItemIndex(22));
            repo.ApplicationUnderTest.TxtBusinessEmail.PressKeys(GL_BusinessEmail);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtBusinessWebAddress' at Center.", repo.ApplicationUnderTest.TxtBusinessWebAddressInfo, new RecordItemIndex(23));
            repo.ApplicationUnderTest.TxtBusinessWebAddress.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$GL_Business_Web_Add' with focus on 'ApplicationUnderTest.TxtBusinessWebAddress'.", repo.ApplicationUnderTest.TxtBusinessWebAddressInfo, new RecordItemIndex(24));
            repo.ApplicationUnderTest.TxtBusinessWebAddress.PressKeys(GL_Business_Web_Add);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BgGrey2CardBody.TxtBusinessFEINSSN' at Center.", repo.ApplicationUnderTest.BgGrey2CardBody.TxtBusinessFEINSSNInfo, new RecordItemIndex(25));
            repo.ApplicationUnderTest.BgGrey2CardBody.TxtBusinessFEINSSN.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$GL_FEINNo' with focus on 'ApplicationUnderTest.BgGrey2CardBody.TxtBusinessFEINSSN'.", repo.ApplicationUnderTest.BgGrey2CardBody.TxtBusinessFEINSSNInfo, new RecordItemIndex(26));
            repo.ApplicationUnderTest.BgGrey2CardBody.TxtBusinessFEINSSN.PressKeys(GL_FEINNo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BgGrey2CardBody.ChkSameAddress' at Center.", repo.ApplicationUnderTest.BgGrey2CardBody.ChkSameAddressInfo, new RecordItemIndex(27));
            repo.ApplicationUnderTest.BgGrey2CardBody.ChkSameAddress.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BgGrey2CardBody.ChkSameAddress' at Center.", repo.ApplicationUnderTest.BgGrey2CardBody.ChkSameAddressInfo, new RecordItemIndex(28));
            //repo.ApplicationUnderTest.BgGrey2CardBody.ChkSameAddress.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BgGrey2CardBody.TxtMailingAddress1' at Center.", repo.ApplicationUnderTest.BgGrey2CardBody.TxtMailingAddress1Info, new RecordItemIndex(29));
            //repo.ApplicationUnderTest.BgGrey2CardBody.TxtMailingAddress1.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$GL_MailingAddress1' with focus on 'ApplicationUnderTest.BgGrey2CardBody.TxtMailingAddress1'.", repo.ApplicationUnderTest.BgGrey2CardBody.TxtMailingAddress1Info, new RecordItemIndex(30));
            //repo.ApplicationUnderTest.BgGrey2CardBody.TxtMailingAddress1.EnsureVisible();
            //Keyboard.Press(GL_MailingAddress1);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BgGrey2CardBody.TxtMailingAddress2' at Center.", repo.ApplicationUnderTest.BgGrey2CardBody.TxtMailingAddress2Info, new RecordItemIndex(31));
            //repo.ApplicationUnderTest.BgGrey2CardBody.TxtMailingAddress2.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$GL_MailingAddress2' with focus on 'ApplicationUnderTest.BgGrey2CardBody.TxtMailingAddress2'.", repo.ApplicationUnderTest.BgGrey2CardBody.TxtMailingAddress2Info, new RecordItemIndex(32));
            //repo.ApplicationUnderTest.BgGrey2CardBody.TxtMailingAddress2.PressKeys(GL_MailingAddress2);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtMailingCity' at Center.", repo.ApplicationUnderTest.TxtMailingCityInfo, new RecordItemIndex(33));
            //repo.ApplicationUnderTest.TxtMailingCity.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$GL_CityName' with focus on 'ApplicationUnderTest.TxtMailingCity'.", repo.ApplicationUnderTest.TxtMailingCityInfo, new RecordItemIndex(34));
            //repo.ApplicationUnderTest.TxtMailingCity.PressKeys(GL_CityName);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtMailingZipCode' at Center.", repo.ApplicationUnderTest.TxtMailingZipCodeInfo, new RecordItemIndex(35));
            //repo.ApplicationUnderTest.TxtMailingZipCode.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$GL_MailingZipcode' with focus on 'ApplicationUnderTest.TxtMailingZipCode'.", repo.ApplicationUnderTest.TxtMailingZipCodeInfo, new RecordItemIndex(36));
            //repo.ApplicationUnderTest.TxtMailingZipCode.PressKeys(GL_MailingZipcode);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SelectMailingState' at 103;21.", repo.ApplicationUnderTest.SelectMailingStateInfo, new RecordItemIndex(37));
            //repo.ApplicationUnderTest.SelectMailingState.Click("103;21");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Search' at 90;13.", repo.ApplicationUnderTest.SearchInfo, new RecordItemIndex(38));
            //repo.ApplicationUnderTest.Search.Click("90;13");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$GL_MailingStateName' with focus on 'ApplicationUnderTest.Search'.", repo.ApplicationUnderTest.SearchInfo, new RecordItemIndex(39));
            //repo.ApplicationUnderTest.Search.PressKeys(GL_MailingStateName);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'ApplicationUnderTest.Search'.", repo.ApplicationUnderTest.SearchInfo, new RecordItemIndex(40));
            //repo.ApplicationUnderTest.Search.PressKeys("{Return}");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(41));
            //Delay.Duration(3000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MainContentHolder.UseAsIs' at Center.", repo.ApplicationUnderTest.MainContentHolder.UseAsIsInfo, new RecordItemIndex(42));
            //repo.ApplicationUnderTest.MainContentHolder.UseAsIs.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtExpirationDate' at Center.", repo.ApplicationUnderTest.TxtExpirationDateInfo, new RecordItemIndex(43));
            repo.ApplicationUnderTest.TxtExpirationDate.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$GL_ExpirationDate' with focus on 'ApplicationUnderTest.TxtExpirationDate'.", repo.ApplicationUnderTest.TxtExpirationDateInfo, new RecordItemIndex(44));
            repo.ApplicationUnderTest.TxtExpirationDate.PressKeys(GL_ExpirationDate);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtInsuranceCarrier' at 29;9.", repo.ApplicationUnderTest.TxtInsuranceCarrierInfo, new RecordItemIndex(45));
            repo.ApplicationUnderTest.TxtInsuranceCarrier.Click("29;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$GL_InsuranceCarrier' with focus on 'ApplicationUnderTest.TxtInsuranceCarrier'.", repo.ApplicationUnderTest.TxtInsuranceCarrierInfo, new RecordItemIndex(46));
            repo.ApplicationUnderTest.TxtInsuranceCarrier.PressKeys(GL_InsuranceCarrier);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtGeneralRemarks' at 178;26.", repo.ApplicationUnderTest.TxtGeneralRemarksInfo, new RecordItemIndex(47));
            repo.ApplicationUnderTest.TxtGeneralRemarks.Click("178;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$GL_GeneralRemark' with focus on 'ApplicationUnderTest.TxtGeneralRemarks'.", repo.ApplicationUnderTest.TxtGeneralRemarksInfo, new RecordItemIndex(48));
            repo.ApplicationUnderTest.TxtGeneralRemarks.PressKeys(GL_GeneralRemark);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
