///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sid_FCGAProject.GL_Product
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GL_FWCI_CTRPage recording.
    /// </summary>
    [TestModule("254b258f-b966-4552-a755-d878e127d03a", ModuleType.Recording, 1)]
    public partial class GL_FWCI_CTRPage : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repository.
        /// </summary>
        public static global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repo = global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository.Instance;

        static GL_FWCI_CTRPage instance = new GL_FWCI_CTRPage();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GL_FWCI_CTRPage()
        {
            GL_FWCI_CTRValue = "2.34";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GL_FWCI_CTRPage Instance
        {
            get { return instance; }
        }

#region Variables

        string _GL_FWCI_CTRValue;

        /// <summary>
        /// Gets or sets the value of variable GL_FWCI_CTRValue.
        /// </summary>
        [TestVariable("28fd9542-2501-434b-925d-e7a2de1624d2")]
        public string GL_FWCI_CTRValue
        {
            get { return _GL_FWCI_CTRValue; }
            set { _GL_FWCI_CTRValue = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Irpm' at Center.", repo.ApplicationUnderTest.IrpmInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Irpm.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(1));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ConsentToRateCTR2' at Center.", repo.ApplicationUnderTest.ConsentToRateCTR2Info, new RecordItemIndex(2));
            repo.ApplicationUnderTest.ConsentToRateCTR2.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '(null)' on item 'ApplicationUnderTest.Txtsearch4'.", repo.ApplicationUnderTest.Txtsearch4Info, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Txtsearch4.Element.SetAttributeValue("Value", null);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$GL_FWCI_CTRValue' with focus on 'ApplicationUnderTest.Txtsearch4'.", repo.ApplicationUnderTest.Txtsearch4Info, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Txtsearch4.PressKeys(GL_FWCI_CTRValue);
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Irpm' at Center.", repo.ApplicationUnderTest.IrpmInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.Irpm.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
