///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sid_FCGAProject.GL_Product
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GLEffectivedate recording.
    /// </summary>
    [TestModule("3e88eaa2-141e-4fd5-b6a6-bae65ab7c7cc", ModuleType.Recording, 1)]
    public partial class GLEffectivedate : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repository.
        /// </summary>
        public static global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repo = global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository.Instance;

        static GLEffectivedate instance = new GLEffectivedate();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GLEffectivedate()
        {
            GL_Effectivedate = "";
            Status_Reason = "Risk Level Effective date";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GLEffectivedate Instance
        {
            get { return instance; }
        }

#region Variables

        string _GL_Effectivedate;

        /// <summary>
        /// Gets or sets the value of variable GL_Effectivedate.
        /// </summary>
        [TestVariable("77750fca-1d6f-4793-bed7-630e117aabee")]
        public string GL_Effectivedate
        {
            get { return _GL_Effectivedate; }
            set { _GL_Effectivedate = value; }
        }

        string _Status_Reason;

        /// <summary>
        /// Gets or sets the value of variable Status_Reason.
        /// </summary>
        [TestVariable("45a8d9b1-a083-4844-828a-4250ee29b51d")]
        public string Status_Reason
        {
            get { return _Status_Reason; }
            set { _Status_Reason = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtEffectiveDate' at Center.", repo.ApplicationUnderTest.TxtEffectiveDateInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.TxtEffectiveDate.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '(null)' on item 'ApplicationUnderTest.TxtEffectiveDate'.", repo.ApplicationUnderTest.TxtEffectiveDateInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.TxtEffectiveDate.Element.SetAttributeValue("Value", null);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '$GL_Effectivedate' on item 'ApplicationUnderTest.TxtEffectiveDate'.", repo.ApplicationUnderTest.TxtEffectiveDateInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.TxtEffectiveDate.Element.SetAttributeValue("Value", GL_Effectivedate);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
