///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sid_FCGAProject.GL_Product
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GLQuickStartQuestion recording.
    /// </summary>
    [TestModule("83500d03-e5af-4028-8cc5-aaee0dca96d5", ModuleType.Recording, 1)]
    public partial class GLQuickStartQuestion : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repository.
        /// </summary>
        public static global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repo = global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository.Instance;

        static GLQuickStartQuestion instance = new GLQuickStartQuestion();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GLQuickStartQuestion()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GLQuickStartQuestion Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MyTable.GQNo2No' at Center.", repo.ApplicationUnderTest.MyTable.GQNo2NoInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.MyTable.GQNo2No.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MyTable.GQNo3No' at Center.", repo.ApplicationUnderTest.MyTable.GQNo3NoInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.MyTable.GQNo3No.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MyTable.LabelTagNo' at Center.", repo.ApplicationUnderTest.MyTable.LabelTagNoInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.MyTable.LabelTagNo.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MyTable.GQNo4No' at Center.", repo.ApplicationUnderTest.MyTable.GQNo4NoInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.MyTable.GQNo4No.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MyTable.GQNo5No' at Center.", repo.ApplicationUnderTest.MyTable.GQNo5NoInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.MyTable.GQNo5No.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MyTable.GQNo6Yes' at Center.", repo.ApplicationUnderTest.MyTable.GQNo6YesInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.MyTable.GQNo6Yes.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MyTable.LabelTagNo1' at Center.", repo.ApplicationUnderTest.MyTable.LabelTagNo1Info, new RecordItemIndex(6));
            repo.ApplicationUnderTest.MyTable.LabelTagNo1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BtnSave1' at Center.", repo.ApplicationUnderTest.BtnSave1Info, new RecordItemIndex(7));
            repo.ApplicationUnderTest.BtnSave1.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
