///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sid_FCGAProject.WC_Product
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BM_CreditDebitFactor recording.
    /// </summary>
    [TestModule("26fcae38-3741-48f1-8364-e00eaf6db373", ModuleType.Recording, 1)]
    public partial class BM_CreditDebitFactor : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repository.
        /// </summary>
        public static global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repo = global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository.Instance;

        static BM_CreditDebitFactor instance = new BM_CreditDebitFactor();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BM_CreditDebitFactor()
        {
            BM_CreDebtFactor = "1.34";
            Status_Reason = "Benchmark Debit / Credit Factor";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BM_CreditDebitFactor Instance
        {
            get { return instance; }
        }

#region Variables

        string _BM_CreDebtFactor;

        /// <summary>
        /// Gets or sets the value of variable BM_CreDebtFactor.
        /// </summary>
        [TestVariable("3be68e36-c366-46ed-98b0-fff5af70a323")]
        public string BM_CreDebtFactor
        {
            get { return _BM_CreDebtFactor; }
            set { _BM_CreDebtFactor = value; }
        }

        string _Status_Reason;

        /// <summary>
        /// Gets or sets the value of variable Status_Reason.
        /// </summary>
        [TestVariable("56394071-fb19-4633-9f3f-6e633c66cf17")]
        public string Status_Reason
        {
            get { return _Status_Reason; }
            set { _Status_Reason = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(0));
            //Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BM_IRPM_Enabled' at Center.", repo.ApplicationUnderTest.BM_IRPM_EnabledInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.BM_IRPM_Enabled.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '$BM_CreDebtFactor' on item 'ApplicationUnderTest.BM_IRPM_Enabled'.", repo.ApplicationUnderTest.BM_IRPM_EnabledInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.BM_IRPM_Enabled.Element.SetAttributeValue("Value", BM_CreDebtFactor);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
