///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;

using WinForms = System.Windows.Forms;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;
using FCGA_Insurance;


namespace Sid_FCGAProject.Common
{

}
namespace Sid_FCGAProject.Common
{
    public partial class AgentOpenBrowser
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
        public static void Hardclosebrowser()
       {
        	
        	Process[] AllProcesses = Process.GetProcesses();
            foreach (var process in AllProcesses)
            {
                if (process.MainWindowTitle != "")
                {
                    string s = process.ProcessName.ToLower();
                    if (s == "chrome")
                        process.Kill();
                }
            }
       	 //Process[] processNames = Process.GetProcessesByName("chrome");
         //foreach (Process item in processNames)
         //{
        //   item.Kill();
        // }
       }

        public void RestorePageClose(RepoItemInfo buttonInfo, RepoItemInfo buttonInfo1)
        {
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'buttonInfo' at Center.", buttonInfo);
            //buttonInfo.FindAdapter<Button>().Click();
            if(buttonInfo.Exists()){
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'buttonInfo1' at Center.", buttonInfo1);
            buttonInfo1.FindAdapter<Button>().Click();
            }
        }
    }
}
