///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sid_FCGAProject.WC_Product.IndustryQuestion
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AmusementandRecreationServicesIQ recording.
    /// </summary>
    [TestModule("178770ef-d621-4689-8dd9-c739445587a4", ModuleType.Recording, 1)]
    public partial class AmusementandRecreationServicesIQ : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repository.
        /// </summary>
        public static global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repo = global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository.Instance;

        static AmusementandRecreationServicesIQ instance = new AmusementandRecreationServicesIQ();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AmusementandRecreationServicesIQ()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AmusementandRecreationServicesIQ Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.FitnessCenter' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.FitnessCenterInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.FitnessCenter.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.AthleticClub' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.AthleticClubInfo, new RecordItemIndex(1));
            //repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.AthleticClub.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.CorporateFitnessCenter' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.CorporateFitnessCenterInfo, new RecordItemIndex(2));
            //repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.CorporateFitnessCenter.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.PersonalTrainerStudio' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.PersonalTrainerStudioInfo, new RecordItemIndex(3));
            //repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.PersonalTrainerStudio.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.PersonalTrainerStudio' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.PersonalTrainerStudioInfo, new RecordItemIndex(4));
            //repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.PersonalTrainerStudio.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.Pilates' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.PilatesInfo, new RecordItemIndex(5));
            //repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.Pilates.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.AerobicStudio' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.AerobicStudioInfo, new RecordItemIndex(6));
            //repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.AerobicStudio.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q1Other' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q1OtherInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q1Other.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q1Otherdesc' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q1OtherdescInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q1Otherdesc.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'OK' with focus on 'ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q1Otherdesc'.", repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q1OtherdescInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q1Otherdesc.PressKeys("OK");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q2Yes' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q2YesInfo, new RecordItemIndex(10));
            //repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q2Yes.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q2No' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q2NoInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q2No.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q3Yes' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q3YesInfo, new RecordItemIndex(12));
            //repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q3Yes.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q3No' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q3NoInfo, new RecordItemIndex(13));
            repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q3No.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q4Yes' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q4YesInfo, new RecordItemIndex(14));
            //repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q4Yes.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q4No' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q4NoInfo, new RecordItemIndex(15));
            repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q4No.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q5Yes' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q5YesInfo, new RecordItemIndex(16));
            //repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q5Yes.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q5No' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q5NoInfo, new RecordItemIndex(17));
            repo.ApplicationUnderTest.IndustryQuestionTable.AmusementandRecreationServices.IQ_Amusement_Q5No.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BtnNext' at 24;16.", repo.ApplicationUnderTest.BtnNextInfo, new RecordItemIndex(18));
            repo.ApplicationUnderTest.BtnNext.Click("24;16");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
