///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sid_FCGAProject.WC_Product.IndustryQuestion
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AutomobileIQ recording.
    /// </summary>
    [TestModule("3d166ab1-4500-4384-83ff-7dbb6d648571", ModuleType.Recording, 1)]
    public partial class AutomobileIQ : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repository.
        /// </summary>
        public static global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repo = global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository.Instance;

        static AutomobileIQ instance = new AutomobileIQ();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AutomobileIQ()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AutomobileIQ Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.Automobile.ATVs' at 13;6.", repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.ATVsInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.ATVs.Click("13;6");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.Automobile.Busses' at 11;10.", repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.BussesInfo, new RecordItemIndex(1));
            //repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.Busses.Click("11;10");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.Automobile.Cars' at 10;10.", repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.CarsInfo, new RecordItemIndex(2));
            //repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.Cars.Click("10;10");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.Automobile.Motorcycles' at 7;4.", repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.MotorcyclesInfo, new RecordItemIndex(3));
            //repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.Motorcycles.Click("7;4");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.Automobile.HeavyVehiclesEquipmentOver2Ton' at 8;6.", repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.HeavyVehiclesEquipmentOver2TonInfo, new RecordItemIndex(4));
            //repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.HeavyVehiclesEquipmentOver2Ton.Click("8;6");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.Automobile.Motorhomes' at 5;5.", repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.MotorhomesInfo, new RecordItemIndex(5));
            //repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.Motorhomes.Click("5;5");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.Automobile.RecreationalVehicles' at 13;7.", repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.RecreationalVehiclesInfo, new RecordItemIndex(6));
            //repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.RecreationalVehicles.Click("13;7");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.Automobile.SemiTrailers' at 14;10.", repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.SemiTrailersInfo, new RecordItemIndex(7));
            //repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.SemiTrailers.Click("14;10");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.Automobile.Trucks' at 6;11.", repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.TrucksInfo, new RecordItemIndex(8));
            //repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.Trucks.Click("6;11");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.Automobile.Vans' at 12;1.", repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.VansInfo, new RecordItemIndex(9));
            //repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.Vans.Click("12;1");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.Automobile.LabelTagOther' at 8;9.", repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.LabelTagOtherInfo, new RecordItemIndex(10));
            //repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.LabelTagOther.Click("8;9");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q1_OtherDesc' at 42;30.", repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q1_OtherDescInfo, new RecordItemIndex(11));
            //repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q1_OtherDesc.Click("42;30");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'OK' with focus on 'ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q1_OtherDesc'.", repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q1_OtherDescInfo, new RecordItemIndex(12));
            //repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q1_OtherDesc.PressKeys("OK");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q2Yes' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q2YesInfo, new RecordItemIndex(13));
            //repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q2Yes.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q2No' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q2NoInfo, new RecordItemIndex(14));
            repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q2No.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q3Yes' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q3YesInfo, new RecordItemIndex(15));
            //repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q3Yes.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q3No' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q3NoInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q3No.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q4Yes' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q4YesInfo, new RecordItemIndex(17));
            //repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q4Yes.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q4No' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q4NoInfo, new RecordItemIndex(18));
            repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q4No.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q5Yes' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q5YesInfo, new RecordItemIndex(19));
            //repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q5Yes.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q5No' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q5NoInfo, new RecordItemIndex(20));
            repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q5No.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q6Yes' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q6YesInfo, new RecordItemIndex(21));
            //repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q6Yes.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q6No' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q6NoInfo, new RecordItemIndex(22));
            repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q6No.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q7Yes' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q7YesInfo, new RecordItemIndex(23));
            //repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q7Yes.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q7No' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q7NoInfo, new RecordItemIndex(24));
            repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q7No.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q8Yes' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q8YesInfo, new RecordItemIndex(25));
            //repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q8Yes.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q8No' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q8NoInfo, new RecordItemIndex(26));
            repo.ApplicationUnderTest.IndustryQuestionTable.Automobile.IQ_Automobile_Q8No.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
