///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sid_FCGAProject.WC_Product.IndustryQuestion
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Inside_Occupations__MiscIQ recording.
    /// </summary>
    [TestModule("2d640fc6-47c6-47b5-b611-5bc46200d05e", ModuleType.Recording, 1)]
    public partial class Inside_Occupations__MiscIQ : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repository.
        /// </summary>
        public static global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repo = global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository.Instance;

        static Inside_Occupations__MiscIQ instance = new Inside_Occupations__MiscIQ();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Inside_Occupations__MiscIQ()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Inside_Occupations__MiscIQ Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.InsideOccupationsMisc.DryCleaningStore' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.InsideOccupationsMisc.DryCleaningStoreInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.IndustryQuestionTable.InsideOccupationsMisc.DryCleaningStore.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.InsideOccupationsMisc.IQ_InsideOccupationsMisc_Q2Yes' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.InsideOccupationsMisc.IQ_InsideOccupationsMisc_Q2YesInfo, new RecordItemIndex(1));
            //repo.ApplicationUnderTest.IndustryQuestionTable.InsideOccupationsMisc.IQ_InsideOccupationsMisc_Q2Yes.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.InsideOccupationsMisc.IQ_InsideOccupationsMisc_Q2No' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.InsideOccupationsMisc.IQ_InsideOccupationsMisc_Q2NoInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.IndustryQuestionTable.InsideOccupationsMisc.IQ_InsideOccupationsMisc_Q2No.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.InsideOccupationsMisc.IQ_InsideOccupationsMisc_Q3Yes' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.InsideOccupationsMisc.IQ_InsideOccupationsMisc_Q3YesInfo, new RecordItemIndex(3));
            //repo.ApplicationUnderTest.IndustryQuestionTable.InsideOccupationsMisc.IQ_InsideOccupationsMisc_Q3Yes.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.InsideOccupationsMisc.IQ_InsideOccupationsMisc_Q3No' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.InsideOccupationsMisc.IQ_InsideOccupationsMisc_Q3NoInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.IndustryQuestionTable.InsideOccupationsMisc.IQ_InsideOccupationsMisc_Q3No.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.InsideOccupationsMisc.IQ_InsideOccupationsMisc_Q4No' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.InsideOccupationsMisc.IQ_InsideOccupationsMisc_Q4NoInfo, new RecordItemIndex(5));
            //repo.ApplicationUnderTest.IndustryQuestionTable.InsideOccupationsMisc.IQ_InsideOccupationsMisc_Q4No.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.InsideOccupationsMisc.IQ_InsideOccupationsMisc_Q4Yes' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.InsideOccupationsMisc.IQ_InsideOccupationsMisc_Q4YesInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.IndustryQuestionTable.InsideOccupationsMisc.IQ_InsideOccupationsMisc_Q4Yes.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.InsideOccupationsMisc.IQ_InsideOccupationMisc_Q5Yes' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.InsideOccupationsMisc.IQ_InsideOccupationMisc_Q5YesInfo, new RecordItemIndex(7));
            //repo.ApplicationUnderTest.IndustryQuestionTable.InsideOccupationsMisc.IQ_InsideOccupationMisc_Q5Yes.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.IndustryQuestionTable.InsideOccupationsMisc.IQ_InsideOccupationsMisc_Q5No' at Center.", repo.ApplicationUnderTest.IndustryQuestionTable.InsideOccupationsMisc.IQ_InsideOccupationsMisc_Q5NoInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.IndustryQuestionTable.InsideOccupationsMisc.IQ_InsideOccupationsMisc_Q5No.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
